# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  

  desc "自动增加构建版本号"
  lane :bump_build_version do
    # 获取当前的构建版本号
    current_build_number = get_build_number(
      xcodeproj: "Twine by SwiftGG.xcodeproj"
    )
    
    # 将构建版本号加1
    increment_build_number(
      build_number: (current_build_number.to_i + 1).to_s,
      xcodeproj: "Twine by SwiftGG.xcodeproj"
    )
  end

  desc "增加产品版本号 (marketing version)"
  lane :bump_product_version do |options|
    # 确保提供了新版本号
    if options[:version].nil?
      UI.user_error!("请提供新的版本号，例如: fastlane bump_product_version version:1.0.1")
    end
    
    # 更新版本号
    increment_version_number(
      version_number: options[:version],
      xcodeproj: "Twine by SwiftGG.xcodeproj"
    )
  end
end
